// 模拟数据
export const mockVehicleData = [
  {
    id: '1',
    license_plate: '甘A12345',
    vehicle_type: '中型货车',
    unloading_type: '机械卸货',
    driver_name: '驾驶员1',
    driver_phone: '13800138000',
    cargo_departure: '甘肃省兰州市',
    estimated_arrival: '2025-08-11T08:00:00Z',
    intended_stall: '水果区1号',
    assigned_stall: '水果区1号-A3',
    cargo_type: '水果',
    cargo_name: '油桃',
    cargo_weight: '500',
    has_attendant: true,
    is_imported: false,
    stall_contact: '张xx',
    stall_phone: '13812345678'
  },
  {
    id: '2',
    license_plate: '甘B67890',
    vehicle_type: '三轮车',
    unloading_type: '人工卸货',
    driver_name: '驾驶员2',
    driver_phone: '13900139000',
    cargo_departure: '甘肃省嘉峪关市',
    estimated_arrival: '2025-08-10T10:30:00Z',
    intended_stall: '蔬菜区2号',
    assigned_stall: '蔬菜区2号-B5',
    cargo_type: '蔬菜',
    cargo_name: '莴笋',
    cargo_weight: '250',
    has_attendant: true,
    is_imported: false,
    stall_contact: '李xx',
    stall_phone: '13987654321'
  },
  {
    id: '3',
    license_plate: '甘C54321',
    vehicle_type: '私家车',
    unloading_type: '混合卸货',
    driver_name: '驾驶员3',
    driver_phone: '13700137000',
    cargo_departure: '甘肃省金昌市',
    estimated_arrival: '2025-08-09T14:45:00Z',
    intended_stall: '肉类区3号',
    assigned_stall: '肉类区3号-C2',
    cargo_type: '肉类',
    cargo_name: '猪肉',
    cargo_weight: '200',
    has_attendant: true,
    is_imported: false,
    stall_contact: '王xx',
    stall_phone: '13756789012'
  },
  {
    id: '4',
    license_plate: '甘D19545',
    vehicle_type: '小型货车',
    unloading_type: '机械卸货',
    driver_name: '驾驶员5',
    driver_phone: '18611112222',
    cargo_departure: '甘肃省白银市',
    estimated_arrival: '2025-08-04T13:40:00Z',
    intended_stall: '蔬菜区3号',
    assigned_stall: '蔬菜区3号-A2',
    cargo_type: '蔬菜',
    cargo_name: '娃娃菜',
    cargo_weight: '325',
    has_attendant: true,
    is_imported: false,
    stall_contact: '赵xx',
    stall_phone: '13623456789'
  },
  {
    id: '5',
    license_plate: '甘E45641',
    vehicle_type: '大型货车',
    unloading_type: '机械卸货',
    driver_name: '驾驶员5',
    driver_phone: '13123456789',
    cargo_departure: '甘肃省酒泉市',
    estimated_arrival: '2025-08-02T17:41:00Z',
    intended_stall: '水果区2号',
    assigned_stall: '水果区2号-C1',
    cargo_type: '水果',
    cargo_name: '西瓜',
    cargo_weight: '415',
    has_attendant: true,
    is_imported: false,
    stall_contact: '陆xx',
    stall_phone: '13590123456'
  },
  {
    id: '6',
    license_plate: '甘F78952',
    vehicle_type: '私家车',
    unloading_type: '人工卸货',
    driver_name: '驾驶员6',
    driver_phone: '17788889999',
    cargo_departure: '甘肃省金昌市',
    estimated_arrival: '2025-08-09T18:35:00Z',
    intended_stall: '肉类区1号',
    assigned_stall: '肉类区1号-B2',
    cargo_type: '肉类',
    cargo_name: '羊肉',
    cargo_weight: '340',
    has_attendant: true,
    is_imported: false,
    stall_contact: '顾xx',
    stall_phone: '13467890123'
  },
  {
    id: '7',
    license_plate: '甘G51374',
    vehicle_type: '中型货车',
    unloading_type: '人工卸货',
    driver_name: '驾驶员3',
    driver_phone: '18800001111',
    cargo_departure: '甘肃省张掖市',
    estimated_arrival: '2025-08-01T11:25:00Z',
    intended_stall: '蔬菜区1号',
    assigned_stall: '蔬菜区1号-C3',
    cargo_type: '蔬菜',
    cargo_name: '油麦菜',
    cargo_weight: '425',
    has_attendant: true,
    is_imported: false,
    stall_contact: '尹xx',
    stall_phone: '17834567890'
  },
  {
    id: '8',
    license_plate: '甘H41286',
    vehicle_type: '中型货车',
    unloading_type: '混合卸货',
    driver_name: '驾驶员8',
    driver_phone: '13579246810',
    cargo_departure: '甘肃省武威市',
    estimated_arrival: '2025-07-28T12:47:00Z',
    intended_stall: '蔬菜区2号',
    assigned_stall: '蔬菜区2号-C2',
    cargo_type: '蔬菜',
    cargo_name: '西红柿',
    cargo_weight: '425',
    has_attendant: true,
    is_imported: false,
    stall_contact: '胡xx',
    stall_phone: '18845678901'
  },
  {
    id: '9',
    license_plate: '甘J54321',
    vehicle_type: '三轮车',
    unloading_type: '人工卸货',
    driver_name: '驾驶员9',
    driver_phone: '14725836901',
    cargo_departure: '甘肃省定西市',
    estimated_arrival: '2025-07-21T09:23:00Z',
    intended_stall: '肉类区3号',
    assigned_stall: '肉类区3号-C1',
    cargo_type: '肉类',
    cargo_name: '牛肉',
    cargo_weight: '425',
    has_attendant: true,
    is_imported: false,
    stall_contact: '郭xx',
    stall_phone: '18656789012'
  }
];